use_frameworks!

platform :ios, '8.0'

target 'YYFlutterModule_Example' do
  pod 'YYFlutterModule', :path => '../'
  pod 'YYModel'

  target 'YYFlutterModule_Tests' do
    inherit! :search_paths

    
  end
end

flutter_application_path = '../flutter_module'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
